package org.example.entity.concrete;

public enum Category {
    BREAKFAST, DINNER, DESSERT, LUNCH, APPETIZER, SNACK, DRINK, SALAD, SOUP, SIDE_DISH, SAUCE, BREAD, PASTA, MEAT, HERB, SPICE, CONDIMENTS, CHICKEN, SEAFOOD, VEGETABLE, FRUIT, NUT, BEVERAGE, NONE
}
