package org.example.entities.concretes;

public enum CategoryConcrete {
    BREAKFAST, LUNCH, DINNER, DESSERT, APPETIZER, SNACK, DRINK, SALAD, SOUP, SAUCE, SIDE_DISH, BREAD, PASTA, MEAT, POULTRY, SEAFOOD, VEGETABLE, FRUIT, NUT, HERB, SPICE, CONDIMENTS, BEVERAGE, NONE
}
