package org.example.entities.concretes;

public enum TagConcrete {
    SPICY, SWEET, SOUR, SALTY, BITTER, FRESH, COLD, HOT, QUICK, EASY, HARD, HEALTHY, UNHEALTHY, VEGETARIAN, VEGAN, GLUTEN_FREE //, DAIRY_FREE, NUT_FREE, EGG_FREE, FISH_FREE, SHELLFISH_FREE, PEANUT_FREE, SOY_FREE, WHEAT_FREE, CRUSTACEAN_FREE, CELERY_FREE, MUSTARD_FREE, SESAME_FREE, LUPIN_FREE, MOLLUSC_FREE, ALCOHOL_FREE, KOSHER, HALAL, ORGANIC, FAIR_TRADE, LOCAL, FARM_TO_FORK, FARM_TO_FAMILY, FARM_TO_FRIEND, FARM_TO_FOOD
}
