package org.example.entities.concretes;

public enum Unit {
    BOTTLE, CAN, CUP, TABLESPOON, TEASPOON, KILOGRAM, LITER, PIECE//, GALLON, MILLILITER, OUNCE, PINT, POUND, QUART, COUNT, PIECE, SLICE, HANDFUL, BUNCH, PINCH, PACKAGE, BAG, BOX, DOZEN, HEAD, SPRIG, STALK, LEAF, WHOLE, HALF, QUARTER
}
